name: notarize-sample-asset

on:
  push:
    branches: [main]

jobs:
  notarize-sample-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Notarize sample asset
        #--> Run the GitHub action
        uses: codenotary/cas-notarize-asset-github-action@main
        with:
          # Whatever asset is being notarized, can be a target/ or dist/ compiled binary or any type of file
          asset: Asset.txt
          cas_api_key: ${{ secrets.CAS_API_KEY }}
